// One-time generator: tools/solar-source.json -> public/js/icons.js
// Emits every Solar glyph (o = outline, b = bold) plus a few hand-drawn
// primitives (plus/check/x/chevrons/trash/pencil/eye/copy/shield) the set lacks.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const src = JSON.parse(fs.readFileSync(path.join(here, 'solar-source.json'), 'utf8'));

const PRIMITIVES = {
  plus: { o: '<path d="M12 5v14M5 12h14" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" fill="none"/>' },
  check: { o: '<path d="M5 12.5l4.2 4.2L19 7" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" fill="none"/>' },
  x: { o: '<path d="M6 6l12 12M18 6L6 18" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" fill="none"/>' },
  'chevron-down': { o: '<path d="M6 9.5l6 6 6-6" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" fill="none"/>' },
  'chevron-right': { o: '<path d="M9.5 6l6 6-6 6" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" fill="none"/>' },
  trash: { o: '<path d="M4.5 6.5h15M9.5 6V4.8c0-.7.6-1.3 1.3-1.3h2.4c.7 0 1.3.6 1.3 1.3V6M7 6.5l.8 12c.05.9.8 1.5 1.7 1.5h5c.9 0 1.65-.6 1.7-1.5l.8-12M10 10.5v6M14 10.5v6" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" fill="none"/>' },
  pencil: { o: '<path d="M4.5 19.5l.9-3.6c.06-.25.19-.48.37-.66L15.9 5.1a2 2 0 0 1 2.83 0l.17.17a2 2 0 0 1 0 2.83L8.76 18.23a1.5 1.5 0 0 1-.66.37l-3.6.9zM14.5 6.5l3 3" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" fill="none"/>' },
  eye: { o: '<path d="M2.5 12S6 5.5 12 5.5 21.5 12 21.5 12 18 18.5 12 18.5 2.5 12 2.5 12z" stroke="currentColor" stroke-width="1.6" fill="none"/><circle cx="12" cy="12" r="3" stroke="currentColor" stroke-width="1.6" fill="none"/>' },
  'eye-closed': { o: '<path d="M3.5 14.5C5.5 16.5 8.4 18 12 18s6.5-1.5 8.5-3.5M6 16.5l-1.5 2M18 16.5l1.5 2M12 18v2.5M4 4l16 16" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" fill="none"/>' },
  copy: { o: '<rect x="8.5" y="8.5" width="11" height="11" rx="2.5" stroke="currentColor" stroke-width="1.6" fill="none"/><path d="M5.5 15.5c-.6 0-1-.5-1-1v-9c0-1.1.9-2 2-2h9c.6 0 1 .4 1 1" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" fill="none"/>' },
  shield: { o: '<path d="M12 3l7 2.6v5.2c0 4.5-3 8.6-7 10.2-4-1.6-7-5.7-7-10.2V5.6L12 3z" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round" fill="none"/>' },
  menu: { o: '<path d="M4 7h16M4 12h16M4 17h16" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" fill="none"/>' },
  'check-circle': { o: '<circle cx="12" cy="12" r="8.2" stroke="currentColor" stroke-width="1.6" fill="none"/><path d="M8.4 12.2l2.4 2.4 4.8-5" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" fill="none"/>' },
  hand: { o: '<path d="M9 11.5V6.4a1.2 1.2 0 0 1 2.4 0v4.3m0-.3V5.2a1.2 1.2 0 0 1 2.4 0v5.2m0-.5V6.6a1.2 1.2 0 0 1 2.4 0V14c0 3.1-2.1 5.3-5.2 5.3-1.9 0-3.1-.8-4.1-2.2l-2-2.9a1.15 1.15 0 0 1 1.7-1.5l1.4 1.4V8.5a1.2 1.2 0 0 1 2.4 0v3" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" fill="none"/>' },
  ban: { o: '<circle cx="12" cy="12" r="8.2" stroke="currentColor" stroke-width="1.6" fill="none"/><path d="M6.4 6.4l11.2 11.2" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/>' },
};

const out = {};
for (const [name, g] of Object.entries(src.icons)) out[name] = { o: g.o || g.b, b: g.b || g.o };
for (const [name, g] of Object.entries(PRIMITIVES)) out[name] = { o: g.o, b: g.b || g.o };
// Real Solar icons (outline + bold) fetched from Iconify — override the
// hand-drawn primitives so edit/delete/toggle match the nav's Solar set.
try {
  const extra = JSON.parse(fs.readFileSync(path.join(here, 'solar-extra.json'), 'utf8'));
  for (const [name, g] of Object.entries(extra)) out[name] = { o: g.o || g.b, b: g.b || g.o };
} catch { /* run tools/fetch-solar-icons.mjs first */ }

const banner = '// GENERATED by tools/extract-icons.mjs — Solar icon set (Design System v2 canonical) + primitives. Do not hand-edit.\n' +
  '// SECURITY INVARIANT: icon() injects ONLY these committed static glyphs via innerHTML.\n' +
  '// Never pass user- or file-derived strings into icon(); render those with textContent.\n';
const body = 'export const ICONS = ' + JSON.stringify(out) + ';\n' +
  'export function icon(name, opts = {}) {\n' +
  "  const { size = 18, active = false, cls = '' } = opts;\n" +
  '  const g = ICONS[name] || ICONS.file;\n' +
  '  const b = active ? g.b : g.o;\n' +
  "  const span = document.createElement('span');\n" +
  "  span.className = 'icm-icon' + (cls ? ' ' + cls : '');\n" +
  '  span.innerHTML = `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" aria-hidden="true">${b}</svg>`;\n' +
  '  return span;\n' +
  '}\n';
const dest = path.join(here, '..', 'public', 'js', 'icons.js');
fs.mkdirSync(path.dirname(dest), { recursive: true });
fs.writeFileSync(dest, banner + body, 'utf8');
console.log('wrote', dest, Object.keys(out).length, 'icons');
